
version: "3.8"

services:
  php7.4.0:
    image: php:7.4.0-fpm
    networks:
      - demo-network
    volumes:
      - ./code/:/var/www/html/
    ports:
      - 9102:9000
  php7.4.30:
    image: php:7.4-fpm-alpine3.15
    networks:
      - demo-network
    volumes:
      - ./code/:/var/www/html/
    ports:
      - 9103:9000 

  nginx:
    image: nginx:latest #指定镜像的名字
    networks:
      - demo-network
    depends_on:
      - php7.4.0
      - php7.4.30
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx
      - ./code/:/var/www/html/
    ports:
      - 8180:80
      - 8181:81

   
networks:
  demo-network:
